name: Forkbuntu
version: '24.04'
paths:
  iso: ubuntu-24.04-live-server-amd64.iso
  output: forkbuntu.iso
autoinstall:
  packages:
    - cowsay
  late-commands:
    - cp -r /cdrom/scripts /target/root
    - curtin in-target -- sh /root/scripts/run_postinstall.sh
